version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
